# Define the stages of the pipeline
stages:
  - build
  - deploy

# Define variables for the pipeline
variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# Define the build stage
build:
  stage: build
  script:
    # Build the Docker image
    - docker build -t $DOCKER_IMAGE .
    # Push the Docker image to the registry
    - docker push $DOCKER_IMAGE

# Define the deploy stage
deploy:
  stage: deploy
  script:
    # Apply the Kubernetes deployment manifest
    - kubectl apply -f kubernetes/deployment.yaml
    # Apply the Kubernetes service manifest
    - kubectl apply -f kubernetes/service.yaml