services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: amir
      POSTGRES_PASSWORD: amir
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: