# Define a Service resource
apiVersion: v1
kind: Service
metadata:
  # Name of the service
  name: flask-app-service
spec:
  selector:
    # Label to match pods with this service
    app: flask-app
  ports:
    - protocol: TCP
      # Port to expose on the service
      port: 80
      # Target port on the pods
      targetPort: 5000
  # Type of service to create (LoadBalancer)
  type: LoadBalancer